/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{
  //   type: 'autogenerated',
  //   dirName: '.'
  // }],

  // But you can create a sidebar manually

  flutterSidebar: [
    {
      type: 'category',
      label: 'Primer parcial',
      items: [
        'flutter/flutter1',
        {
          type: 'category',
          label: 'Lenguaje Dart',
          items: [
              'flutter/flutter2',
              'flutter/flutter3',
              'flutter/flutter4',
          ]
        },
        'flutter/flutter5',
        'flutter/flutter6',
        'flutter/flutter7',
        'flutter/flutter-exam1',
      ]
    }
  ],

  androidSidebar: [
    'android/android1',
    {
      type: 'category',
      label: 'Primer parcial',
      items: [
        'android/android2',
        'android/android3',
        'android/android4',
        {
          type: 'category',
          label: 'Layouts',
          items: [
            'android/android5',
            'android/android6',
            'android/android7',
          ]
        },
        'android/android8',
        'android/android9',
        'android/android10',
        'android/exam1',
      ],
    },
    {
      type: 'category',
      label: 'Segundo Parcial',
      items: [
        'android/android11',
        'android/android12',
        'android/android13',
        'android/android14',
        'android/android15',
        'android/android16',
      ]
    },
  ],

};

module.exports = sidebars;
